---
name: Lint

on: [push]

jobs:
  lint:
    name: Lint scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update shellcheck
        run: sudo apt install -y shellcheck
      - name: Lint scripts
        run: shellcheck *.sh
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install unbound
        run: sudo apt install -y unbound
      - name: Validate Compose Files
        run: find . -name "*.conf" -print0 | xargs -0 -n1 unbound-checkconf  -f
